### ISSUE TITLE
환경 설정

### ISSUE THREAD

**Issue by SyngChoi** [kiworkshop/Pascal#11]
환경 변수를 설정합니다.

**Comment by kwangilcho** [comment]
![ezgif-2-96c399df3f7a](https://user-images.githubusercontent.com/12382114/50449485-06b22680-096b-11e9-92a8-d8291fcbdbe9.gif)
![ezgif-2-03684ac7171c](https://user-images.githubusercontent.com/12382114/50449556-7aecca00-096b-11e9-8e13-07008d9c81d4.gif)
![ezgif-2-bb15461eb889](https://user-images.githubusercontent.com/12382114/50449783-e1261c80-096c-11e9-9a63-6f317c1bafe8.gif)
