### ISSUE TITLE
문자열 입력 컴포넌트에서 되돌리기 기능 추가

### ISSUE THREAD

**Issue by Deocksoo** [kiworkshop/Pascal#29]
'검색 및 분류 ' 버튼 누른 이후에 버튼을 누르기 이전 상태로 되돌리는 기능이 구현되면 좋겠습니다.
방법 1 : 입력한 상품 문자열을 backup 해둔 뒤 재사용하는 방법
방법 2 : 추가하기와 덮어쓰기 기능으로 구분하고 검색 및 분류 이후에도 문자열을 남겨두어 덮어쓰는 방법

**Comment by kwangilcho** [comment]
stepper componet를 사용하면서 해결된 이슈입니다.
닫습니다.
