### ISSUE TITLE
특정 분류 영역에서 검색하는 기능 추가

### ISSUE THREAD

**Issue by Deocksoo** [kiworkshop/Pascal#38]
특정 분류를 지정해놓고 문자열을 입력하는 경우에, 입력받은 문자열이 고시명칭인지 비고시명칭인지 지정된 분류 내에서만 검색할 수 있도록 하여야 합니다.

**Comment by kwangilcho** [comment]
1. 지정상품을 국문, 영문으로 검색합니다.

![ezgif-2-e31d3ff22cb7](https://user-images.githubusercontent.com/12382114/50447324-ae285c80-095d-11e9-9433-b8152483b673.gif)

**Comment by kwangilcho** [comment]
2. 특정 분류 내에서 지정상품을 검색합니다.

![ezgif-2-4f98705ec8a6](https://user-images.githubusercontent.com/12382114/50447350-da43dd80-095d-11e9-9675-e32b129b05a9.gif)

**Comment by kwangilcho** [comment]
3. 검색한 상품을 추가합니다.
![ezgif-2-9310a55189c4](https://user-images.githubusercontent.com/12382114/50447373-03fd0480-095e-11e9-96da-40e3af97300f.gif)
