### ISSUE TITLE
상품관리에서 상품의 고시 여부를 변경시 주의해야할 사항을 표현해야합니다.

### ISSUE THREAD

**Issue by kwangilcho** [kiworkshop/Pascal#68]
현재는 수정된 상품의 고시/비고시 여부를 자동으로 판단하지 않습니다.
그러므로  고시상품에서 비고시상품으로, 비고시상품에서 고시상품으로
상품 데이터를 수정 후에 반드시 고시/비고시 여부를 사용자가 "수동으로" 관리해주어야합니다.

따라서 사용자가 이를 인지할 수 있도록 주의 사항 문구가 들어가면 좋을 것 같습니다.

**Comment by kwangilcho** [comment]
![image](https://user-images.githubusercontent.com/12382114/49336302-b503ce00-f642-11e8-8cfa-17dfca3bcc6c.png)

**Comment by Deocksoo** [comment]
괜찮은 방식인것 같습니다!

**Comment by kwangilcho** [comment]
![ezgif-2-1c95c88a13b3](https://user-images.githubusercontent.com/12382114/50448494-02830a80-0965-11e9-8ef7-7103eef0663d.gif)
![ezgif-2-2ea36ca9da80](https://user-images.githubusercontent.com/12382114/50448811-9c978280-0966-11e9-93a4-b0bd6eb0989d.gif)
