### ISSUE TITLE
상품 추가 기능

### ISSUE THREAD

**Issue by SyngChoi** [kiworkshop/Pascal#7]
Briefcase 컴포넌트의 선택된 지정상품 목록에 상품 명칭을 추가합니다.
<br>

__1. 지정상품 목록은 다음 필드를 포함하고 있어야 합니다.__
- 국문명칭
- 영문명칭
- 분류
- 유사군 코드
- 고시명칭/비고시명칭 여부
<br>

__2. 상품 추가 기능은 대화창이 아닌 컴포넌트 형태로 하여서 하나의 페이지로 보이게끔 구현합니다. 상품 추가 컴포넌트는 아래와 같은 서브컴포넌트들로 구성됩니다.__
- 지정상품 목록을 문자열 데이터를 입력받는 컴포넌트
- 고시명칭으로 추가할 상품 리스트
- 비고시명칭으로 추가할 상품 리스트

**Comment by kwangilcho** [comment]
![ezgif-2-2a1c79d01610](https://user-images.githubusercontent.com/12382114/50447573-78847300-095f-11e9-8dc3-03621e8382a6.gif)
![ezgif-2-fc9cd46610d6](https://user-images.githubusercontent.com/12382114/50447575-79b5a000-095f-11e9-8a98-550cd1040f9a.gif)
![ezgif-2-b08bb06a5e49](https://user-images.githubusercontent.com/12382114/50447576-7ae6cd00-095f-11e9-8cff-531ac9ff5cdb.gif)
